/* tslint:disable */
/* eslint-disable */
/**
 * RanobeNet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EpisodeDtoForMe
 */
export interface EpisodeDtoForMe {
    /**
     * 
     * @type {number}
     * @memberof EpisodeDtoForMe
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof EpisodeDtoForMe
     */
    chapterId: number;
    /**
     * 
     * @type {string}
     * @memberof EpisodeDtoForMe
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EpisodeDtoForMe
     */
    story: string;
}

export function EpisodeDtoForMeFromJSON(json: any): EpisodeDtoForMe {
    return EpisodeDtoForMeFromJSONTyped(json, false);
}

export function EpisodeDtoForMeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpisodeDtoForMe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'chapterId': json['chapterId'],
        'title': json['title'],
        'story': json['story'],
    };
}

export function EpisodeDtoForMeToJSON(value?: EpisodeDtoForMe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'chapterId': value.chapterId,
        'title': value.title,
        'story': value.story,
    };
}

