/* tslint:disable */
/* eslint-disable */
/**
 * RanobeNet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NovelDtoForSave
 */
export interface NovelDtoForSave {
    /**
     * 
     * @type {string}
     * @memberof NovelDtoForSave
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NovelDtoForSave
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof NovelDtoForSave
     */
    author?: string | null;
}

export function NovelDtoForSaveFromJSON(json: any): NovelDtoForSave {
    return NovelDtoForSaveFromJSONTyped(json, false);
}

export function NovelDtoForSaveFromJSONTyped(json: any, ignoreDiscriminator: boolean): NovelDtoForSave {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'author': !exists(json, 'author') ? undefined : json['author'],
    };
}

export function NovelDtoForSaveToJSON(value?: NovelDtoForSave | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'author': value.author,
    };
}

