/* tslint:disable */
/* eslint-disable */
/**
 * RanobeNet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NovelDtoForPublicListing,
    NovelDtoForPublicListingFromJSON,
    NovelDtoForPublicListingFromJSONTyped,
    NovelDtoForPublicListingToJSON,
} from './NovelDtoForPublicListing';

/**
 * 
 * @export
 * @interface UserDtoForPublic
 */
export interface UserDtoForPublic {
    /**
     * 
     * @type {number}
     * @memberof UserDtoForPublic
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserDtoForPublic
     */
    name: string;
    /**
     * 
     * @type {Array<NovelDtoForPublicListing>}
     * @memberof UserDtoForPublic
     */
    novels: Array<NovelDtoForPublicListing>;
}

export function UserDtoForPublicFromJSON(json: any): UserDtoForPublic {
    return UserDtoForPublicFromJSONTyped(json, false);
}

export function UserDtoForPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDtoForPublic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'novels': ((json['novels'] as Array<any>).map(NovelDtoForPublicListingFromJSON)),
    };
}

export function UserDtoForPublicToJSON(value?: UserDtoForPublic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'novels': ((value.novels as Array<any>).map(NovelDtoForPublicListingToJSON)),
    };
}

