/* tslint:disable */
/* eslint-disable */
/**
 * RanobeNet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDtoForSave
 */
export interface UserDtoForSave {
    /**
     * 
     * @type {string}
     * @memberof UserDtoForSave
     */
    name: string;
}

export function UserDtoForSaveFromJSON(json: any): UserDtoForSave {
    return UserDtoForSaveFromJSONTyped(json, false);
}

export function UserDtoForSaveFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDtoForSave {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UserDtoForSaveToJSON(value?: UserDtoForSave | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

