/* tslint:disable */
/* eslint-disable */
/**
 * RanobeNet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EpisodeDtoForPublic
 */
export interface EpisodeDtoForPublic {
    /**
     * 
     * @type {number}
     * @memberof EpisodeDtoForPublic
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EpisodeDtoForPublic
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EpisodeDtoForPublic
     */
    story: string;
}

export function EpisodeDtoForPublicFromJSON(json: any): EpisodeDtoForPublic {
    return EpisodeDtoForPublicFromJSONTyped(json, false);
}

export function EpisodeDtoForPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpisodeDtoForPublic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'story': json['story'],
    };
}

export function EpisodeDtoForPublicToJSON(value?: EpisodeDtoForPublic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'story': value.story,
    };
}

