/* tslint:disable */
/* eslint-disable */
/**
 * RanobeNet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NovelDtoForPublicListing,
    NovelDtoForPublicListingFromJSON,
    NovelDtoForPublicListingFromJSONTyped,
    NovelDtoForPublicListingToJSON,
} from './NovelDtoForPublicListing';

/**
 * 
 * @export
 * @interface NovelDtoForPublicListingPagedList
 */
export interface NovelDtoForPublicListingPagedList {
    /**
     * 
     * @type {number}
     * @memberof NovelDtoForPublicListingPagedList
     */
    readonly currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof NovelDtoForPublicListingPagedList
     */
    readonly totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof NovelDtoForPublicListingPagedList
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof NovelDtoForPublicListingPagedList
     */
    readonly totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof NovelDtoForPublicListingPagedList
     */
    readonly hasPrevious: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NovelDtoForPublicListingPagedList
     */
    readonly hasNext: boolean;
    /**
     * 
     * @type {Array<NovelDtoForPublicListing>}
     * @memberof NovelDtoForPublicListingPagedList
     */
    items: Array<NovelDtoForPublicListing>;
}

export function NovelDtoForPublicListingPagedListFromJSON(json: any): NovelDtoForPublicListingPagedList {
    return NovelDtoForPublicListingPagedListFromJSONTyped(json, false);
}

export function NovelDtoForPublicListingPagedListFromJSONTyped(json: any, ignoreDiscriminator: boolean): NovelDtoForPublicListingPagedList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentPage': json['currentPage'],
        'totalPages': json['totalPages'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'hasPrevious': json['hasPrevious'],
        'hasNext': json['hasNext'],
        'items': ((json['items'] as Array<any>).map(NovelDtoForPublicListingFromJSON)),
    };
}

export function NovelDtoForPublicListingPagedListToJSON(value?: NovelDtoForPublicListingPagedList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pageSize': value.pageSize,
        'items': ((value.items as Array<any>).map(NovelDtoForPublicListingToJSON)),
    };
}

