/* tslint:disable */
/* eslint-disable */
/**
 * RanobeNet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDtoForPublicListing
 */
export interface UserDtoForPublicListing {
    /**
     * 
     * @type {number}
     * @memberof UserDtoForPublicListing
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserDtoForPublicListing
     */
    name: string;
}

export function UserDtoForPublicListingFromJSON(json: any): UserDtoForPublicListing {
    return UserDtoForPublicListingFromJSONTyped(json, false);
}

export function UserDtoForPublicListingFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDtoForPublicListing {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function UserDtoForPublicListingToJSON(value?: UserDtoForPublicListing | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

