/* tslint:disable */
/* eslint-disable */
/**
 * RanobeNet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDtoForMe
 */
export interface UserDtoForMe {
    /**
     * 
     * @type {number}
     * @memberof UserDtoForMe
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserDtoForMe
     */
    name: string;
}

export function UserDtoForMeFromJSON(json: any): UserDtoForMe {
    return UserDtoForMeFromJSONTyped(json, false);
}

export function UserDtoForMeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDtoForMe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function UserDtoForMeToJSON(value?: UserDtoForMe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

